baseURL = "https://kevinjihwanlee.com/"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "Kevin Lee (이지환)"

[blackfriday]
extensions = ["hardLineBreak"]

[permalinks]
fixed = ":title/"
posts = "posts/:slug/"

[params]
author = "Kevin Lee"
description = "Kevin Lee is a computer science student at Northwestern University. "
bio = "Computer Science \nNorthwestern University"
avatar = "img/linkedin.jpg"
favicon = "img/favicon.png"

	[params.contact]
    email = "kevinlee2020@u.northwestern.edu"
    github = "kevinjihwanlee"
    resume = "kevin_lee_resume.pdf"
